### ISSUE TITLE
Foreground colour of the TextBox when editing a DataGrid cell

### ISSUE THREAD

**Issue by ColinWaddell** [DanPristupov/WpfThemes#5]
Hello. Just looking to make something a little more readable.

When using the DataGrid control and editing a cell's contents, the foreground colour used for the text is black.

![image](https://cloud.githubusercontent.com/assets/1848325/10280736/22fcd43e-6b67-11e5-91c1-5e98ead717c4.png)

Thanks for making up this theme, it's made the rest of my app look awesome.

**Comment by TanyaPristupova** [comment]
Hi ColinWaddell. Thank you for using DarkBlendTheme. I’m going to be really busy during this week. But I definitely will have a look at the issue on the weekend.

**Comment by ColinWaddell** [comment]
Many thanks Tanya.

If you need an example project to replicate just let me know and I'll push something to my account for you.

**Comment by ColinWaddell** [comment]
Accidentally clicked "close". My apologies.

**Comment by TanyaPristupova** [comment]
Hi Colin.
This is not as easy as I expected, still working on that. I'll let you know when it is fixed.

**Comment by ColinWaddell** [comment]
Cheers @TanyaPristupova 

I've had a shot myself but got nowhere. If I find another moment to hack away at the stylesheet I'll let you know if I have any success.

**Comment by TanyaPristupova** [comment]
Hi ColinWaddell,
In order to fix cell foreground color we have to change EditingElementStyle in DataGridTextColumn. 
Since DataGridTextColumn does not derive from FrameworkElement I can’t create a style for it in DarkBlendTheme. But you can try the following workaround:

```
<Window.Resources>
   <Style x:Key="TextBoxStyle1" TargetType="{x:Type TextBox}">
        <Setter Property="Foreground" Value="{StaticResource ForegroundBrush}"/>
   </Style>
</Window.Resources>
    <Grid>
        <DataGrid AutoGenerateColumns="False">
            <DataGrid.Columns>
               <!-- Here go your columns-->
                <DataGridTextColumn Header="Header" Binding="{Binding Name}" EditingElementStyle="{StaticResource TextBoxStyle1}" />
            </DataGrid.Columns>
        </DataGrid>
    </Grid>
```

It is not beautiful, but it works on my machine. Please, let me know if it helps.

**Comment by ColinWaddell** [comment]
Hi @TanyaPristupova 

Just tested out your fix and it works perfectly.

Thanks for taking the time to look into this for me!
